### ISSUE TITLE
IWillUnmount lifecycle method

### ISSUE THREAD

**Issue by jonase** [weavejester/brutha#2]
Hi @weavejester 

Is there a specific reason why the [componentWillUnmount](https://facebook.github.io/react/docs/component-specs.html#unmounting-componentwillunmount) lifecycle method is not exposed as a protocol?

**Comment by weavejester** [comment]
There isn't an `unmount` function yet, so there are currently no unmount semantics.

**Comment by weavejester** [comment]
Fixed in 10a6069e83.
